import java.util.Scanner;

public class GenerateCSV {

	public static void main(String[] args) {
		int customrownum = 0;

		
		//Valid data that can be inputed 
		String customdatstr = "NULL";
		float customdatnum = 0;
		String customdatdate = "00/00/0000"; //No date support in Eclipse
		
		//Start 
		
		
		//Create Cols
		System.out.println("Enter How Many Coloumns You Would Like Generated?");
		Scanner colnum = new Scanner(System.in);
		int customcolnum = colnum.nextInt();	
		System.out.println("You Have Entered " + customcolnum + " Coloumns, Continue? YES/NO");
		Scanner yesnoscnr = new Scanner(System.in);	
		char yes = yesnoscnr.next("Y|y|N|n").charAt(0);
		if (yes == 'Y'|| yes == 'y') {
			  System.out.println ("YOU HAVE ENTERED YES");
			}
		
		else if (yes == 'N' || yes == 'n') {
			  System.out.println ("YOU HAVE ENTERED NO");
		}
		
		/*

		System.out.println("Please Enter The Maximum Amount Of Rows Generated By This Program");
		System.out.println("You Have Entered " + customrownum + " Rows, Continue YES/NO?");
		System.out.println("Please Select Which Data Type For the Coloumn"); //Need to loop for each coloumn
		
		//Enter data for each row, TODO
		System.out.println("Please Enter Your Data For The First Coloumn From 1 To " + customrownum );
		System.out.println(customrownum + " Created");
		System.out.println("All Data For " + customrownum + " Entered Succefully!");
		
		
		//Write To CSV File, TODO
		System.out.println("Writing Data...........");
		System.out.println("DONE!");
		System.out.println("ERROR!");
		TEST TEST
		*/
	}

}
